### ISSUE TITLE
Can Load Plugin Error

### ISSUE THREAD

**Issue by jevincen61** [SteveMHill/ClassificationTool#4]
Couldn't load plugin 'ClassificationTool' due to an error when calling its classFactory() method

**Comment by Diego635** [comment]
I got this error:

> Couldn't load plugin 'ClassificationTool' due to an error when calling its initGui() method 
> 
> TypeError: setValue(self, val: int): argument 1 has unexpected type 'float' 
> Traceback (most recent call last):
>   File "/Applications/MacPorts/QGIS3-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 514, in startPlugin
>     plugins[packageName].initGui()
>   File "/Users/Diego_NQ/Library/Application Support/QGIS/QGIS3/profiles/profile1/python/plugins/ClassificationTool/ClassificationTool.py", line 190, in initGui
>     self.getOptions()
>   File "/Users/Diego_NQ/Library/Application Support/QGIS/QGIS3/profiles/profile1/python/plugins/ClassificationTool/ClassificationTool.py", line 431, in getOptions
>     self.dlg.sb_rf_min_sample.setValue(2.0)
> TypeError: setValue(self, val: int): argument 1 has unexpected type 'float'
> 
> 
> Python version: 3.12.10 (main, Apr 12 2025, 04:06:31) [Clang 16.0.0 (clang-1600.0.26.6)] 
> QGIS version: 3.40.5-Bratislava Bratislava, exported
